# Generated by Django 3.2.5 on 2021-08-01 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenders', '0003_auto_20210801_1234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participants',
            options={'verbose_name': 'Participant', 'verbose_name_plural': 'Participants'},
        ),
        migrations.AlterModelOptions(
            name='procuringorganization',
            options={'verbose_name': 'Procuring Organization', 'verbose_name_plural': 'Procuring Organizations'},
        ),
        migrations.AlterModelOptions(
            name='redflags',
            options={'verbose_name': 'Red Flag', 'verbose_name_plural': 'Red Flags'},
        ),
        migrations.AlterModelOptions(
            name='tender',
            options={'verbose_name': 'Tender', 'verbose_name_plural': 'Tenders'},
        ),
    ]
